version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      FLASK_ENV: development  # Thiết lập môi trường nếu cần
    depends_on:
      - redis  # Nếu bạn có sử dụng Redis cho SocketIO

  # Nếu bạn cần Redis cho SocketIO
  redis:
    image: "redis:alpine"
