name: Deploy Server in branch master

on:
  push:
    branches:
      - master

jobs:
  builder:
    name: Build Images
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build, tag, and save image
        id: build-image
        env:
          IMAGE_NAME: ${{ secrets.IMAGE_NAME }}
          USERNAME_DOCKERHUB: ${{ secrets.USERNAME_DOCKERHUB }}

        run: |
          docker build -t $USERNAME_DOCKERHUB/$IMAGE_NAME:latest .

      - name: Log in to Docker Hub
        env:
          USERNAME_DOCKERHUB: ${{ secrets.USERNAME_DOCKERHUB }}
          PASSWORD_DOCKERHUB: ${{ secrets.PASSWORD_DOCKERHUB }}
        run: |
          docker login -u $USERNAME_DOCKERHUB -p $PASSWORD_DOCKERHUB

      - name: Push Docker image
        env:
          IMAGE_NAME: ${{ secrets.IMAGE_NAME }}
          USERNAME_DOCKERHUB: ${{ secrets.USERNAME_DOCKERHUB }}
        run: |
          docker push $USERNAME_DOCKERHUB/$IMAGE_NAME:latest

      - name: SSH into the server and pull Docker image
        uses: appleboy/scp-action@master
        env:
          IMAGE_NAME: ${{ secrets.IMAGE_NAME }}
          USERNAME_DOCKERHUB: ${{ secrets.USERNAME_DOCKERHUB }}
        with:
          host: ${{ secrets.HOST }}
          port: ${{secrets.PORT}}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          command: |
            docker pull $USERNAME_DOCKERHUB/$IMAGE_NAME:latest

  copy_files:
    name: Copy Files Into Server
    runs-on: ubuntu-latest
    needs: builder

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Copy stack.yml to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.PORT}}
          source: docker-compose.yml
          target: /home/${{ secrets.USERNAME }}/deployment/

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: copy_files

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Deploy Docker container
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.PORT}}
          script: |
            docker stack rm ${{ secrets.STACK_NAME }}
            docker stack deploy -c /home/${{ secrets.USERNAME }}/deployment/docker-compose.yml ${{ secrets.STACK_NAME }}
